# Configuration for ADV Extractor
# Firms are loaded from adv_extract_firms.yaml and adv_extract_firms-*.yaml files

# Column identifiers
SEC_ID_COLUMN: 1D
CRD_ID_COLUMN: 1E1

# Matching strategy for finding firms
# Options: "SEC_ONLY", "CRD_ONLY", "BOTH"
MATCHING_STRATEGY: "BOTH"

# Date columns that should not be treated as integers
DATE_COLUMNS:
  - DateSubmitted   # Date the filing was submitted
  - Execution Date  # Date the filing was executed

# Target columns to extract (order determines output CSV columns)
TARGET_COLUMNS:
  # "Item 5 Information About Your Advisory Business - Employees, Clients, and Compensation"
  - 5A        # Total number of employees
  - 5B1       # Number of investment adviser representatives (IP headcount)
  # - 5B2     # Number of non-investment adviser representative employees
  # - 5B3     # Number of clerical employees
  # - 5B4     # Number of employees registered with a broker-dealer
  # - 5B5     # Number of employees who are solicitors
  # - 5B6     # Number of employees who are other
  - 5C1       # Number of clients that are high net worth individuals
  - 5C2       # Number of clients that are other individuals
  - 5D1f      # Number of clients that are other investment advisers
  # - 5D1g    # Number of clients that are insurance companies
  # - 5D1h    # Number of clients that are pension and profit sharing plans
  # - 5D1i    # Number of clients that are charitable organizations
  # - 5D1j    # Number of clients that are corporations or other businesses
  # - 5D1k    # Number of clients that are other
  - 5D3f      # Regulatory assets under management
  # - 5D3g    # Regulatory assets under management for insurance companies
  # - 5D3h    # Regulatory assets under management for pension and profit sharing plans
  # - 5D3i    # Regulatory assets under management for charitable organizations
  # - 5D3j    # Regulatory assets under management for corporations or other businesses
  # - 5D3k    # Regulatory assets under management for other
  - 5F2a      # Total regulatory assets under management
  - 5F2b      # Regulatory assets under management from non-US clients
  - 5F2c      # Regulatory assets under management from US clients
  - 5F2d      # Number of non-US clients
  - 5F2e      # Regulatory assets under management from non-US clients
  - 5F2f      # Number of US clients
  - 5F3       # Regulatory assets under management from US clients
# "Do you have custody of any advisory clients"
  - 9A2a      # Regulatory assets under management from private funds
  - 9A2b      # Number of private fund clients
  - 9B2a      # Regulatory assets under management from other pooled investment vehicles
  - 9B2b      # Number of other pooled investment vehicle clients

# Download settings
DOWNLOAD_DELAY_SECONDS: 0.5  # Delay between downloads to avoid throttling
BROWSER_SESSION_WAIT_SECONDS: 1.0  # Wait time after establishing browser session
BROWSER_DOWNLOAD_WAIT_SECONDS: 0.5  # Wait time after attempting download
MAX_RETRIES: 3  # Number of retry attempts for downloads

# Timeout settings (in seconds)
PAGE_LOAD_TIMEOUT: 120     # Maximum time to wait for page to load
DOWNLOAD_TIMEOUT: 1800     # Maximum time to wait for download to complete (30 min for large files)
SCRIPT_TIMEOUT: 60         # Maximum time to wait for JavaScript execution

# Download URLs and file sizes for automatic data acquisition
DOWNLOAD_URLS:
  2024_monthly:
    - url: "https://www.sec.gov/files/adv-filing-data-20241201-20241231.zip"
      description: "December 2024 (4.8 MB)"
    - url: "https://www.sec.gov/files/adv-filing-data-20241101-20241130.zip"
      description: "November 2024 (5.3 MB)"
    - url: "https://www.sec.gov/files/adv_filing_data_20241001_20241031.zip"
      description: "October 2024 (7.8 MB)"
    - url: "https://www.sec.gov/adv-filing-data-20240901-20240930.zip"
      description: "September 2024 (6.6 MB)"
    - url: "https://www.sec.gov/files/adv-filing-data-20240801-20240831.zip"
      description: "August 2024 (7.3 MB)"
    - url: "https://www.sec.gov/files/adv-filing-data-20240701-20240731.zip"
      description: "July 2024 (7.5 MB)"
    - url: "https://www.sec.gov/files/adv-filing-data-20240601-20240630.zip"
      description: "June 2024 (7.7 MB)"
    - url: "https://www.sec.gov/adv-filing-data-20240501-20240531.zip"
      description: "May 2024 (8.2 MB)"
    - url: "https://www.sec.gov/files/adv-filing-data-20040401-20240430.zip"
      description: "April 2024 (7.4 MB)"
  2024_q1:
    - url: "https://www.sec.gov/files/form-adv-updates-01012024-03312024.zip"
      description: "Form ADV Updates from January 1, 2024 to March 31, 2024 (43 MB)"
  historical:
    - url: "https://www.sec.gov/foia/docs/adv/form-adv-complete-ria-01012001-120312023.zip"
      description: "RIA 2001-2023 (1.2 GB)"
    - url: "https://www.sec.gov/files/form-adv-complete-era-01012001-120312023.zip"
      description: "ERA 2001-2023 (68 MB)"
